### ISSUE TITLE
[지수] card 컴포넌트 구현

### ISSUE THREAD

**Issue by yoonmallang22** [FRONTENDSCHOOL5/final-18-EarthUs#30]
- [x] props 설정
- [x] 좋아요 기능 개발

**Comment by yoonmallang22** [comment]
- [ ] 업로드한 이미지 없을 경우 버그 수정 (by 신애님💕)

**Comment by JAYCODE-git** [comment]
- [x] 카드에 들어오는 API image 데이터 ',' 문자열 기준으로 split
- [x] 카드에 들어오는 API image 데이터가 1장 이상이라면  Swiper 라이브러리 실행
- [x] 카드를 더 동적으로 사용하기 위해 children, spread props 프로퍼티 추가
